import { Game, Region } from "@/types";
import { Autocomplete, Button, TextField } from "@mui/material";
import axios from "axios";
import { styled } from "goober";
import Head from "next/head";
import { useForm } from "react-hook-form";

const Wrapper = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const Form = styled("div")`
  display: flex;
  flex-direction: column;
  width: 50vw;

  > * {
    margin: 0.3rem;
  }
`;

const Add = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Game>();

  const onSubmit = async (data: Game) => {
    console.log(data);

    await axios.post("/api/add-game", data);
  };

  return (
    <>
      <Head>
        <title>GameDB | Add Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Form>
          <TextField variant="filled" label="Name" {...register("name")} />
          <TextField
            variant="filled"
            label="Platform"
            {...register("platform")}
          />
          <TextField
            variant="filled"
            label="Box Art (URL)"
            {...register("art")}
          />
          <Autocomplete
            options={Object.values(Region)}
            renderInput={(params) => (
              <TextField
                {...params}
                {...register("region")}
                variant="filled"
                label="Region"
              />
            )}
          />
          <TextField
            variant="filled"
            label="Variant(s) (comma separated)"
            {...register("variant")}
          />
          <Button variant="contained" onClick={handleSubmit(onSubmit)}>
            Add Game
          </Button>
        </Form>
      </Wrapper>
    </>
  );
};

export default Add;
