import GameForm, { GameFormData } from "@/components/form/game-form";
import axios from "axios";
import { styled } from "goober";
import Head from "next/head";
import { AddGameParameters } from "./api/add-game";

const Wrapper = styled("div")`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const Add = () => {
  const onSubmit = async (data: GameFormData) => {
    await axios.post<AddGameParameters>("/api/add-game", data);
  };

  return (
    <>
      <Head>
        <title>GameDB | Add Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <GameForm actionText="Add Game" onSubmit={onSubmit} />
      </Wrapper>
    </>
  );
};

export default Add;
